Fixed not showing load more button when there are more transactions available to display.
kaeruB/suzuchi-ginkou-client pull request #19
Opened 2023-02-19 00:05 UTC by kaeruB

2023-02-19 03:31 UTC, kazoogon requested changes

2023-02-19 03:31 UTC, kazoogon commented on src/compositions/transactions/index.tsx
> +      transactionsAndUserDetails &&
```javascript
transactionsAndUserDetails &&
transactionsAndUserDetails.transactions &&
transactionsAndUserDetails.transactions.length <
transactionsAndUserDetails.totalNoOfTransactions &&
transactionsAndUserDetails.totalNoOfTransactions > DEFAULT_HISTORY_ITEMS
```
↓
```javascript
// chyba ok
transactionsAndUserDetails?.transactions?.length < transactionsAndUserDetails?.totalNoOfTransactions &&
transactionsAndUserDetails?.totalNoOfTransactions > DEFAULT_HISTORY_ITEMS
```

za dlugie dana

2023-02-19 03:31 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +  shouldRenderLoadMoreButton: boolean
`shouldRenderLoadMoreButton` 
↓ 
`showMoreButton` albo `showMoreTransactionButton`

dame?

2023-02-19 03:31 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +                  props.transactionsAndUserDetails.usersDetails
uzywaj destructive object w argument
https://javascript.info/destructuring-assignment

`props.transactionsAndUserDetails.userDetails`
↓
`transactionsAndUserDetails.userDetails`

inne code tez

2023-02-19 03:31 UTC, kazoogon commented on src/types/transaction.ts
>  export type TransactionsWithUsersDetails = {
nie widzialem takiego variable hmmmmmmmm
`Transactions` i `UserDetails` powinno byc

2023-02-19 03:31 UTC, kazoogon commented on src/types/transaction.ts
> +  totalNoOfTransactions: number
`NoOf`
o co chodzi??
ogolnie jak dodaje `no` do variable, wyglada troche skomplikowane

`totalTransactions` i `totalNoOfTransactions`

2023-02-19 03:31 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
`userEmailToDetails`
to details ?

2023-02-26 00:17 UTC, kaeruB commented on src/compositions/transactions/TransactionsLayout.tsx
> +                  props.transactionsAndUserDetails.usersDetails
プロジェクトの全体でやらないといけないので、とりあえずTrelloに追加：https://trello.com/c/JU3wZ5JY/36-destructure-props　🙇

2023-02-26 00:21 UTC, kaeruB commented on src/types/transaction.ts
>  export type TransactionsWithUsersDetails = {
これはまた違うPRで直しましょう　[trello](https://trello.com/c/QpBaNij4/37-transactionswithusersdetails-bad-type-fix)

2023-02-26 00:23 UTC, kaeruB commented on src/types/transaction.ts
> +  totalNoOfTransactions: number
NoOf = Number of でした、`totalTransactions`　いいですね 🐈

2023-02-26 00:27 UTC, kaeruB commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
Objectの場合はこんな感じ書きます。例えば、ここの`userEmailToDetails`は：
`{ [userEmail: string]: UserDetails }`
なので、これは mapping of userEmail **to** userDetails → userEmailToDetails
ネットでこのような書き方を見つけましたが、どうですか？

2023-02-26 01:56 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
https://github.com/kaeruB/suzuchi-ginkou-client/blob/3dbea87a9d9146d8df1bc421168fb7ea2823f81c/src/compositions/transactions/TransactionsLayout.tsx#L95-L105

▼ `historyData={props.transactionsAndUserDetails.transactions} ` 
😀 hmm rozumiem, chociaz byloby lepiej gdyby `transactions` byl zamiast `historyData` 

▼ `currency={currency}`
😀 hai rozumiem

▼ `onShowEditModal={onShowEditModal} `
😀 hai okke

▼ `fetchTransactionsAndUserDetails={ 
     props.fetchTransactionsAndUserDetails 
   } `
😀 hai hai

▼ `pairId={props.pairId} `
😀 tak tak

▼ `userEmailToDetails={ 
     props.transactionsAndUserDetails.usersDetails 
   } `
🤔 ❓ email?? nagle pojawia sie email??

2023-02-26 01:57 UTC, kazoogon commented on src/types/transaction.ts
> +  totalNoOfTransactions: number
okej

2023-02-26 01:57 UTC, kazoogon commented on src/types/transaction.ts
>  export type TransactionsWithUsersDetails = {
okej un

2023-02-26 01:57 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +                  props.transactionsAndUserDetails.usersDetails
okej

2023-02-26 02:03 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
jeszcze sa dwa miejsca

https://github.com/kaeruB/suzuchi-ginkou-client/blob/3dbea87a9d9146d8df1bc421168fb7ea2823f81c/src/compositions/transactions/TransactionsLayout.tsx#L75-L82

https://github.com/kaeruB/suzuchi-ginkou-client/blob/3dbea87a9d9146d8df1bc421168fb7ea2823f81c/src/compositions/transactions/TransactionsLayout.tsx#L133-L142

2023-02-26 02:06 UTC, kaeruB commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
確かに、bez sensu 💦  `usersDetails` albo `userEmailToDetails` ですね…

2023-02-26 02:19 UTC, kaeruB commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
もしゅくは、全部`userIdToDetails` ? なんでemialが出てきたな…、emailいらん

2023-02-26 08:39 UTC, kazoogon commented on src/utils/functions/commons.ts
> +export const decodePairUserIds = (pairId: string): [string, string] =>
decode zeby dostac cos nowe dane.
My chcemy wiedziec "cos nowe dane", a nie "decode".
Co dostajemy po decode 🤔 ?

2023-02-26 08:40 UTC, kazoogon commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
`userIdToDetails` o co chodzi `To` ??

2023-03-04 23:48 UTC, kaeruB commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
Wytłumaczyłam [tutaj](https://github.com/kaeruB/suzuchi-ginkou-client/pull/19#discussion_r1117998431)

2023-03-04 23:50 UTC, kaeruB commented on src/compositions/transactions/TransactionsLayout.tsx
> +                userEmailToDetails={
`usersDetails`と`userEmailToDetails`違うpull requestに統一します、ok?

2023-03-04 23:57 UTC, kaeruB commented on src/utils/functions/commons.ts
> +export const decodePairUserIds = (pairId: string): [string, string] =>
`decodePairIdToUserIds`, どうですか？

2023-03-05 03:44 UTC, kazoogon approved these changes

2023-03-05 04:01 UTC, merged